### ISSUE TITLE
Strange behaviour with DST

### ISSUE THREAD

**Issue by FrnchFrgg** [dbuezas/lovelace-plotly-graph-card#100]
DST change happened Sunday morning in my country which uncovered a bug in `plotly-graph`: it generated two points with the same `x` value for the two consecutive hours, which creates a strange graph:
![image](https://user-images.githubusercontent.com/19911152/199083581-2eca3ed0-0224-4d4b-8358-22afa1e1d334.png)

I think an easy way to solve this bug is to always convert dates and times to UTC when generating data points, and if needed converting anew to the local timezone for axes label and tooltip display. I'll try when I have time.

**Comment by dbuezas** [comment]
It went backwards, right?
Another option is to add a null point whenever time seems to go backwards, the lines would at least be disconnected

**Comment by FrnchFrgg** [comment]
No it did not, but that's probably because I am plotting hourly statistics. The graph has two points with the same abscissa. Maybe you can disconnect the trace at non-ordered times, but I think that's a red herring. When fetching historical data the returned result should be time-ordered, and when plotting arbitrary (synthetic) data, restricting to LTR traces may be harmful.

Date and time standards are very explicit on the fact that even in the presence of DST or other idiosyncrasies you can always distinguish seemingly identical hours so that time is still strictly monotonic. In the case of DST I think there is a flag somewhere in the data structure to indicate whether the given time is in the first or second instance of the 2-to-3'oclock time span.

Converting to UTC which will never have DST, or even to EPOCH timestamps, should be enough to avoid the problem.

**Comment by dbuezas** [comment]
Ok, I just read (here)[https://github.com/Avaiga/taipy-gui/issues/473]  that plotly converts dates to local time, so it may indeed suffice to pass date objects and let plotly handle them.
I also find a lot of bug reports

**Comment by dbuezas** [comment]
I also find bug reports related to DST which may or may not have been fixed, so it's a matter or trying then

**Comment by FrnchFrgg** [comment]
I experimented a bit and there is a problem: javascript Date objects are always stored in UTC (they are essentially a class wrapper around the unix timestamp). But `getTimezoneoffset()` does not have its counterpart `setTimezoneoffset()` and instead returns whatever offset corresponds to that time in the local timezone... Which means that passing `Date` objects around will not solve the problem because we cannot force a timezone in them.

A workaround could be to pass vanilla timestamps as straight numbers, then convert back in the axes, tooltip and scatter formatters, but that's a lot of work to fix a bug belonging to plotly itself.

**Comment by dbuezas** [comment]
Wow! You digged very deep!
Thanks for the research, and what a pitty
