### ISSUE TITLE
Data updated through refresh_interval is incorrect

### ISSUE THREAD

**Issue by Masterz69** [dbuezas/lovelace-plotly-graph-card#104]
In summer 2022 started to search replacement for graph card because of that staff - see below. 
Some days ago Plotly cards starts to behave the same.

How it looks on auto-refreshes:
![image](https://user-images.githubusercontent.com/15225823/199467036-77a592fb-6c76-4747-a3f5-b550bb90a895.png)

But actually on manual refresh:
![image](https://user-images.githubusercontent.com/15225823/199467191-b0eb7c49-7af9-4741-9ad3-9a062dd0a768.png)

It started approx. week ago, probably after upgrade to Core 2022.10.4.

**Comment by dbuezas** [comment]
Thanks, I'll take a look

**Comment by Masterz69** [comment]
Some more info.
When page still open in browser - after some time graph become corrupted: like not all data included, but show those steps.
It was not noticed before last week, probably before core 2022.10.4.
As soon I do page refresh or switch between pages - all data appears in graph, as on second screenshot.

**Comment by dbuezas** [comment]
Does the xaxis go to some random time period?
Does it recover if you double click on the plot? 
If so, I have an upcoming fix

**Comment by Masterz69** [comment]
See no issues with xaxis.

Page opened for 15+minutes:
![image](https://user-images.githubusercontent.com/15225823/199569512-c0bf7186-e49d-4239-ae57-d0ac5f7a2542.png)

Double-click - no effect.

Moved littl-bit:
![image](https://user-images.githubusercontent.com/15225823/199569816-01564695-fa02-408b-86e8-f12c9d66a203.png)

Pressing [reset] - see first screenshot.

On page refresh:
![image](https://user-images.githubusercontent.com/15225823/199570018-9783df53-3022-473a-a912-a8ce44c19c05.png)

P.S. Initially this behavior noticed on HA built-in graph card in the middle-2022, then I moved to Plotly and now it appears on Plotly too.

**Comment by dbuezas** [comment]
HA used to return fictitious data point at the end of the requested date range. I was cleaning those up. Maybe the API stopped doing that and we're removing real data when making incremental data updates.

Thanks for the tests and reports, I think this will be solved by Friday

**Comment by dbuezas** [comment]
Fixed in v1.7.2

**Comment by dbuezas** [comment]
Oh, doch, fixed in v1.7.0
