### ISSUE TITLE
Error when viewing statistics

### ISSUE THREAD

**Issue by tomlevels** [dbuezas/lovelace-plotly-graph-card#105]
When I zoom in a lot on old data, I get this error:
Error computing range subtraction. Please report an issue in the repo of this card and share this:[null,null][1644132719037,1644174865402]

Config:
type: custom:plotly-graph
entities:
  - entity: sensor.daily_energy_t1
    statistic: state
    period: auto
    type: bar

**Comment by dbuezas** [comment]
Thanks, fix coming on Friday

**Comment by dbuezas** [comment]
This would be fixed in v1.6.2. please reopen if it persists
