### ISSUE TITLE
Implement pinch to zoom

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#106]
With the upcoming changes that manage the visible range more tightly, it may be finally possible to implement pinch to zoom in the card (even though plotly itself doesn't support it)

**Comment by zanna-37** [comment]
Do you have something in mind? Do you need help with this?

**Comment by dbuezas** [comment]
> Do you have something in mind? 

What I have in mind:
* on touchstart, if two touches are detected
    * store the x and y pixel position of each touch
    * store the "starting" ranges of the plot [like this](https://github.com/dbuezas/lovelace-plotly-graph-card/blob/7ceaceb79326959e8ef9d919b0bedd0b150bef29/src/plotly-graph-card.ts#L269) but also for all yaxes
* on touchmove, if two touches are detected:
    * compute the ratios between the distances between the "starting" and current touches (on each axis independently)
    * compute the difference between the centers of the "starting" and current touches
    * use the ratios to scale and differences to translate (move) the starting ranges and apply those new ranges to the plot
    * apply the new ranges via Plotly.relayout inside a `this.withoutRelayout` (to avoid constant refetching)
* on touchend
    * fetch data
* add a config to disable it in case somebody doesn't like it
This should allow for a natural pinch to zoom and two finger scrolling.

> Do you need help with this?

I have experience with this so I should be able to handle it, but if you have some time and want to give it a shot go for it! :). Just let me know and I'll assign you this  so we don't both do the same thing :)

**Comment by zanna-37** [comment]
I like the idea and I think I'll work. I don't have experience with this, and (as you probably already noted) I don't have much free time to code, unfortunately. =(
If you assign me to this I might take months before doing it.

I asked if you needed help because I like the feature and in case this issue was not on your todo list, I might have tried it eventually, but I can't make promises on when.

**Comment by dbuezas** [comment]
Makes sense.
I have two features I want to make after the filters are merged: this one (pinch to zoom) and allowing lambda style functions in all other parts of the yaml. After that I'll only fox bugs for a while. Meaning, I'll probably tackle pinch to zoom in a week or so

**Comment by dbuezas** [comment]
Since you are interested in the feature, I'll keep you in the loop. I'll probably need an opinion in how it feels and whatnot :)

**Comment by dbuezas** [comment]
So, I gave it a try and it so one can scroll and zoom in specific places (like google maps) and it works well, but I had to grab plotly's svg elements to get the right coordinates and proportions. This means it will be brittle (break with heavily customised plots and plotly updates).

Therefore I won't pursue the "full" multitouch support for now. Instead I'll just do zoom in the center. This feels ok and isn't brittle. Plus one can already scroll with one finger, so functionality wise it should be fine.

One thing I tried was to allow for zooming scales independently, it works but it feels super wonky.

**Comment by dbuezas** [comment]
Oh, I'll add double tap+drag as a zoom gesture too, one handed zoom!

**Comment by dbuezas** [comment]
OMG, single finger zooming is such a pleasure!

**Comment by dbuezas** [comment]
There, update to v2.1.0 and let me know what do you think
