### ISSUE TITLE
When combined with custom:grid-layout, the plot grows out of the screen

### ISSUE THREAD

**Issue by LGO44** [dbuezas/lovelace-plotly-graph-card#110]
plotly card 1.61
Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Interface utilisateur : 20221102.1 - latest

The graph grows very quickly by the right side, the start time (left) doesn't change so that it generates a horizontal scroll bar in the screen  (see the print screen joined)...
Now the card becomes unusable.

![image](https://user-images.githubusercontent.com/95585425/199953710-dc94c977-c71a-4385-8af0-e19ed97d343d.png)

**Comment by LGO44** [comment]
First, thank you for your help.

For my use case the issue is still in the V1.6.2
> I Used it in a layout grid, 
> if it 's in a panel or masonry, or sidebar it's OK
> 

my yaml:

views:
  - theme: Backend-selected
    title: Home
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.wiser_status
          - entity: sensor.wiser_hub_signal_strength
        title: Wiser status
        hours_to_show: 240
        refresh_interval: 15

**Comment by OlePZ9** [comment]
type: custom:plotly-graph
entities:
  - entity: sensor.victron_solarcharger_mppt_250_60_pv_power
    name: Schuppen
  - entity: sensor.victron_solarcharger_pv_power_tracker_0
    name: Hausdach
  - entity: sensor.victron_solarcharger_pv_power_tracker_1
    name: Vordach
  - entity: sensor.victron_pv_power_sum
    fill: tozeroy
  - entity: sensor.victron_system_battery_power_dc
    fill: tozeroy
hours_to_show: 24
refresh_interval: 30
layout:
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 1
          step: minute
        - count: 1
          step: hour
        - count: 12
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day

**Comment by dbuezas** [comment]
Until I get to this, can you try forcing the width in yaml?

```yaml
width: 500
```

**Comment by LGO44** [comment]
The widget not in grid layout the param seems to have no effect

The card run welling vertical layout or horizontal layout

**Comment by OlePZ9** [comment]
Afteri copied the entities in a fresh car, it works. Maybe the feature to be able to switch between different time windows made the issue. That is what I've added to all cards. Thanks for your support!

**Comment by dbuezas** [comment]
> Afteri copied the entities in a fresh car, it works. Maybe the feature to be able to switch between different time windows made the issue. That is what I've added to all cards. Thanks for your support!

Happy to hear you fixed it! Let me know if you stumble on this again and can reproduce it and I'll take a look

**Comment by LGO44** [comment]
I'm sorry, but for me the issue is always active.
even after adding a new dashboard and recreating the card with a custom.grid.

**Comment by dbuezas** [comment]
Hey @LGO44. Thanks for letting me know. Would you provide screenshots, yamls and as much details as possible? :)

**Comment by LGO44** [comment]
Hi David,

The issue happens only in the custom.grid layout

Here is the yaml of a dashboard that has the issue, in this dashboard created specially to test 

views:
  - theme: Backend-selected
    title: Home
    type: **custom:grid-layout**
    badges: []
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sensor.wiser_status
          - entity: sensor.wiser_hub_signal_strength
        title: Wiser status
        hours_to_show: 240
        refresh_interval: 15
        width: 800
  - theme: Backend-selected
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:plotly-graph
        entities:
          - entity: sun.sun
            fill: tozeroy
        hours_to_show: 24
        refresh_interval: 10

screen shot 1 
![image](https://user-images.githubusercontent.com/95585425/200195745-fc719592-506a-49ad-99e7-7ef96fe545cf.png)


screen shot 2 same dashboard, same screen area, 54 second after the first one
![image](https://user-images.githubusercontent.com/95585425/200195802-02ba9975-610a-46b8-9859-0f3582f86d37.png)

If I can help you by anyway feel free to ask me.
Christian

**Comment by LGO44** [comment]
Ok for the new title, 

here is a video that shows the issue, I hope that it will be usefull for you (sorry to be so late)
 It starts with the sidebar and it's OK
I change it on custom. grid-layout : NOK
I come back to side bar and OK

https://user-images.githubusercontent.com/95585425/200384418-318eebc4-b7c7-45d0-843d-ec206922450a.mp4

**Comment by dbuezas** [comment]
Thanks! I installed the custom component and was able to reproduce it.

I think I have the fix too, I just need to test it doesn't break the other layouts and auto sizing. 

The fix will likely come in the next release later this week

**Comment by dbuezas** [comment]
v1.7.2 should make you happy :)

**Comment by LGO44** [comment]
OK now , thanks a lot :)

**Comment by LGO44** [comment]
@dbuezas It seems to have the same behavior on iPhone and the Home assistant application.

**Comment by dbuezas** [comment]
is it back?

**Comment by LGO44** [comment]
I only notice it on my iPhone on the HA application. It 's not back.

**Comment by dbuezas** [comment]
So it still happens on your iPhone but not on Desktop?

**Comment by LGO44** [comment]
Exactly, sorry for not beeing clear.

**Comment by dbuezas** [comment]
I can unfortunately not reproduce it in my Android and have no iPhone at my disposal.

Feel free to rise a new issue specific for iPhones and I'll mark it as `needs help`. Maybe another iPhone user wants to give it a try :)
