### ISSUE TITLE
time range - period mapping not giving correct result (2) 

### ISSUE THREAD

**Issue by netweaver1970** [dbuezas/lovelace-plotly-graph-card#112]
Zooming in from 5minute period gives me a day period ???
SAme YAML as in issue #111 

Start position:
![image](https://user-images.githubusercontent.com/18028618/199979069-3eac0cd4-dae0-42be-83a8-5619f33017bf.png)

zoom in at 03:00 time:
![image](https://user-images.githubusercontent.com/18028618/199979358-fa44a975-3e8c-4835-85d4-b829d336146c.png)

**Comment by dbuezas** [comment]
Same as before. Little m are minutes.
