### ISSUE TITLE
Zooming  (and switching from period hour to period 5minute) in makes my traces disappear

### ISSUE THREAD

**Issue by netweaver1970** [dbuezas/lovelace-plotly-graph-card#113]
Start:
![image](https://user-images.githubusercontent.com/18028618/199982245-da31c497-bc75-4692-a441-d588b262cf53.png)

1 level zoom in (1 notch on mouse scroll wheel):
![image](https://user-images.githubusercontent.com/18028618/199982409-5c68c47a-ef3b-4f07-9bae-2198b9277fa6.png)

1 level zoom out and all traces are back.

Normal 5minute period (just like when selecting using 24h or 3d time range) is working fine

**Comment by dbuezas** [comment]
That may be because home assistant isn't storing those statistics on those periods.
To confirm, check if it is always the same entities and periods which are missing (regardless of period: auto or manually forced interval)

**Comment by netweaver1970** [comment]
yep, that was it. fully approved. all PEBKAC issues so far ... 
With great powers, one needs still proper knowledge to handle them :)

**Comment by dbuezas** [comment]
😂
Happy to hear you got it working. Do you have a suggestion regarding how to save the confusion to the next person?
You are obviously very active, so if it wasn't intuitive for you, it most likely won't be for others either

**Comment by netweaver1970** [comment]
In general, throw more info to the end-user, better to teach them than to automatically correct input errors.
Such as "Are you sure you really mean MINUTES in the time range mapping to period grouping table?"
And then you show the interpretation of the mapping table:

"
      24h (hours): 5minute
      3d (days): 5minute
      7d (days): hour
      14 (days): hour
      1m (MINUTES): day
      3m (MINUTES): day
      12m (MINUTES): week
      36m (MINUTES): month
"

And for the non-existing data, maybe put a message on screen if the selection doesn't return any data. 
Something like this:" No data is present in the database for the current selection ".
Extra help: if the active grouping period is '5minute', then add also this text: "5minute level LTS data is only kept in the database for about 14 days" to the user facing message.

> 😂 Happy to hear you got it working. Do you have a suggestion regarding how to save the confusion to the next person? You are obviously very active, so if it wasn't intuitive for you, it most likely won't be for others either

I wouldn't consider myself a good example. But I agree everyone can get confused, for sure in a 'coding' style card. WYSIWIG is a bit easier in that respect. But a lot more restrictive.
