### ISSUE TITLE
show_value - value is not visible

### ISSUE THREAD

**Issue by Jindra-git** [dbuezas/lovelace-plotly-graph-card#122]
I tried to make several configurations and changes according to the examples but unfortunately with the same result. The value is still displayed off the chart and not visible. My PC is using Edge and I see the same result on my mobile phone in the app. Thanks for any idea where I may be making a mistake in the configuration.

This is my yaml: 

type: custom:plotly-graph
entities:
  - entity: sensor.teplomer_outdoor_park_pressure
    texttemplate: <b> %{y} </b>hPa
    line:
      color: orange
    show_value:
      right_margin: 40
    unit_of_measurement: ' hPa'
refresh_interval: 10
title: Tlak
hours_to_show: 168
layout:
  height: 250
  clicmode: false
  dragmode: false
  showlegend: false
  xaxis:
    nticks: 10
    showticklabels: true
    tickformat: '%d'
  margin:
    t: 10
    l: 55
    r: 30
    b: 50
    pad: 5
config:
  scrollZoom: false
  displayModeBar: false

![2022-11-06 19 23 39](https://user-images.githubusercontent.com/73619654/200188506-0efbd7de-39ff-44ff-b8bd-df6b160eaa56.png)

**Comment by dbuezas** [comment]
Which version are you using? I just released a fix for it 2 hours ago (1.6.3)

**Comment by dbuezas** [comment]
Fixed in v1.6.3
Please reopen if the bug persists :)
