### ISSUE TITLE
previously 'hidden' dataseries disappear after lots of zooming/moving/period changing

### ISSUE THREAD

**Issue by netweaver1970** [dbuezas/lovelace-plotly-graph-card#125]
Hi,
my graph always starts with the outside temperature 'hidden' but still selectable in the legend, whenever I want it.
After some analysing (moving, zooming, all kind of user interactions), sometime the outside temperature disappears from the legend and is not selectable any more.

Start:
![image](https://user-images.githubusercontent.com/18028618/200268450-5a49a62f-ae78-4651-b2aa-6c86b2addbd5.png)

after navigating a lot, look at the missing 'outside' in the legend
![image](https://user-images.githubusercontent.com/18028618/200267762-fdd15301-f5ba-4500-8e29-cc04ab08d214.png)

after pressing the reset button back to the start position:
![image](https://user-images.githubusercontent.com/18028618/200268450-5a49a62f-ae78-4651-b2aa-6c86b2addbd5.png)

**Comment by netweaver1970** [comment]
Extra info, I can reproduce it by just going to the start position (with 'outside') hidden. 
And select the 12 Months range. Then the 'outside' data series completely disappears.
But when I first enable the 'outside' data series, and only then select the 12 Months time range, then the 'outside' data series is stays visible, and it works fine.
In fact, I can reproduce it easier. ALL selected ranges over 3 days are causing the 'outside' to disappear. When I go back to refresh, or I select 3 days, then I get the 'outside' back

**Comment by netweaver1970** [comment]
Some similarities: the default time range is 24 hr. For both the default time range and the 3 days time range (the 2 'correct' time ranges), the graph uses 5 minutes period. As of 7 days time range the period goes to hour and bigger.

**Comment by dbuezas** [comment]
I was able to reproduce this: I'm confident it is because plotlyjs hides the legend of traces with no data. I'll add a fake null data point in that case to avoid the issue.
Fix will come with the next release

**Comment by dbuezas** [comment]
This should not happen anymore in v1.7.2
