### ISSUE TITLE
Duplicate bar

### ISSUE THREAD

**Issue by tomlevels** [dbuezas/lovelace-plotly-graph-card#129]
I have a card that shows the energy consumption, but the bar of the current day seems to be duplicated (also the bar width is very small, it changes to wider after you double click):
![image](https://user-images.githubusercontent.com/3691709/200545978-32f8b901-92f4-4dc1-90a3-55f3ce80c66a.png)

This is my config:
 ```
type: custom:plotly-graph
entities:
  - entity: sensor.airco_beneden_daily
    statistic: state
    period: day
    type: bar
    texttemplate: '%{y}'
hours_to_show: 240
defaults:
  yaxes:
    fixedrange: true
 ```

**Comment by dbuezas** [comment]
Thanks @tomlevels,
this happens because at the moment, the last datapoint is "extended" to the present so line scatter plots look full. This functionality precedes the statistics feature, so I hadn't considered the case you show.

I'm considering making this behaviour configurable. 

In the mean time, you could add a lambda that strips the last value from the ys array:
```js
lamba: (ys) => ys.slice(0, -1)
```
I'll ping you here when there are news, and you can remove the lambda

**Comment by dbuezas** [comment]
by the way, I like how this plot looks. WDYT about dropping the screenshot and yaml as a "Show & Tell" post in the discussions? :)

**Comment by tomlevels** [comment]
I tried the lambda (with a **b**) and it works fine! I also put it on the Show and Tell

**Comment by dbuezas** [comment]
For reference: Show&Tell #131

**Comment by dbuezas** [comment]
> Is it possible to show the actual value for 19:00 till the actual moment?

Mmmmm I think there is:
* add a second trace with the same entity
* do not ask for the statistic or period
* use a lambda to pick the very last elements of x and y

**Comment by dbuezas** [comment]
Looks perfect! you could set the same color and group their legends, but to be honest, the fact that the last one looks different... I'd call that a feature.

BTW, why do you do `ys.slice(-2)` ? shouldn't it be ys.slice(-1)?

**Comment by tomlevels** [comment]
I also thought of making it the same color, but it looked nice like this.
I tried ys.slice(-1), but then I got this (not sure if it is a bug):
![image](https://user-images.githubusercontent.com/3691709/200917443-4be56c1e-8df9-46eb-93bd-17cbed1400b2.png)

**Comment by dbuezas** [comment]
Mmm are you sure you didn't do -2 on both axes instead?
```js
        ...
        /// THIS IS WRONG
        const slicedx = xs.slice(-2) // this is broken because you are grabbing the last two instead of the very last one
        const slicedy = ys.slice(-2)
        ...
```
Instead of:
```js
        ...
        /// THIS IS RIGHT
        const slicedx = xs.slice(-1)
        const slicedy = ys.slice(-1) // gets you the last entry and nothing else
        ...
```

**Comment by tomlevels** [comment]
This is with:
const slicedx = xs.slice(-1)
const slicedy = ys.slice(-1)
![image](https://user-images.githubusercontent.com/3691709/201519350-fc24a5f0-3297-4492-b114-644b73b86e56.png)

This is with:
const slicedx = xs.slice(-1)
const slicedy = ys.slice(-2)
![image](https://user-images.githubusercontent.com/3691709/201519398-51a82fc0-8961-4c87-ad17-75f349c89d02.png)

This is with:
const slicedx = xs.slice(-2)
const slicedy = ys.slice(-2)
![image](https://user-images.githubusercontent.com/3691709/201519426-8b9de8be-9e26-4604-a1cc-dfe1dfa62cb2.png)

I also have no clue why it is working this way.

**Comment by dbuezas** [comment]
Mmm interesting I'll try this myself, likely a bug.

**Comment by dbuezas** [comment]
Oh c**p.
This is because of this fix: https://github.com/dbuezas/lovelace-plotly-graph-card/pull/128/commits/d6ccd98e1119b9538a21b785a8e5d667160a5bdf

Plotly doesn't handle itself well when line plots contain isolated datapoints, so I artificially duplicate points which appear alone. Since you are grabbing the very last point, my "fix" detects that this will create issues and adds a duplicate.
 
 By doing
 ```js
const slicedx = xs.slice(-1)
const slicedy = ys.slice(-2)
```
my fix thinks there are two points and doesn't add the duplicate. 

I could:
* Do that before lambdas, so what you output is what's plotted (which will create problems when you compute derivatives or count things).
* Only do it for entities that are plotting lines (this may work, but i don't like "exceptions to the rule")
* Add a configuration to disable it.
* any other idea?

**Comment by dbuezas** [comment]
For now I will ignore the specific case of a single datapoint being available. In this case, no line will be there to create the "ghosting" effect anyway.

**Comment by dbuezas** [comment]
This should be fixed on v1.7.4. Would you confirm? :)

**Comment by tomlevels** [comment]
As soon as it is available I will test it.

**Comment by tomlevels** [comment]
I just tested, it now works with -1, -1. thanks!

**Comment by dbuezas** [comment]
Thanks!

BTW, you can always force HACS to update the available versions by navigating to the specific component in HACS and then clicking redownload
<img width="215" alt="image" src="https://user-images.githubusercontent.com/777196/201530613-c7c5ac0d-dc41-4f78-bcdc-c3900998b5e2.png">

**Comment by dbuezas** [comment]
BTW, feel free to add your latest results & yaml to your show&tell #131

**Comment by tomlevels** [comment]
I updated the show&tell

**Comment by dbuezas** [comment]
Thanks!

**Comment by tomlevels** [comment]
I am afraid there has been a regression (see current hour):
![image](https://user-images.githubusercontent.com/3691709/202997905-e6a9e5ae-3369-4179-825c-990249b62d43.png)

This is with this code:
```
type: custom:plotly-graph
entities:
  - entity: sensor.airco_beneden_hourly
    statistic: state
    period: hour
    name: Hourly
    type: bar
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(0, -1)
        const slicedy = ys.slice(0, -1)
        slicedx[0].setMinutes(0)
        return {x:slicedx, y:slicedy};
      }
  - entity: sensor.airco_beneden_hourly
    statistic: state
    period: hour
    type: bar
    name: Current hour
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(-1)
        const slicedy = ys.slice(-1)
        slicedx[0].setMinutes(0)
        return {x:slicedx, y:slicedy};
      }
hours_to_show: 8
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
```

The strange thing is when I change the code to this (only change the -1 to -2):
```
type: custom:plotly-graph
entities:
  - entity: sensor.airco_beneden_hourly
    statistic: state
    period: hour
    name: Hourly
    type: bar
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(0, -1)
        const slicedy = ys.slice(0, -1)
        slicedx[0].setMinutes(0)
        return {x:slicedx, y:slicedy};
      }
  - entity: sensor.airco_beneden_hourly
    statistic: state
    period: hour
    type: bar
    name: Current hour
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(-2)
        const slicedy = ys.slice(-2)
        slicedx[0].setMinutes(0)
        return {x:slicedx, y:slicedy};
      }
hours_to_show: 8
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
```

I get this:
![image](https://user-images.githubusercontent.com/3691709/202998283-a64dd6f5-178b-459b-b935-9d8fcf632f24.png)

Any idea what is wrong here?

**Comment by dbuezas** [comment]
Mmmm that looks like plotlyjs is acting up. For some reason it decided to draw the bar very thin. Can you confirm that the plot looks fine in an older version?

**Comment by tomlevels** [comment]
I tried back till version 1.7.5 but they all look the same, very strange. Maybe the cache was not completely reset?

**Comment by tomlevels** [comment]
I tried older versions, but for me it is not clear what version I am running. HACS always shows that I am using the last version, even if I downloaded an older version?

**Comment by tomlevels** [comment]
I now got it working with a workaround:
```
type: custom:plotly-graph
offset: 1h
entities:
  - entity: sensor.airco_beneden_hourly
    statistic: state
    period: hour
    type: bar
    name: Hourly
    texttemplate: '%{y}'
  - entity: sensor.airco_beneden_hourly
    type: bar
    name: Current hour
    texttemplate: '%{y}'
    lambda: |-
      (ys,xs) => {
        const slicedx = xs.slice(-2)
        const slicedy = ys.slice(-2)
        slicedx[0].setMinutes(0)
        slicedy[0] = slicedy[1]
        slicedy[1] = 0
        return {x:slicedx, y:slicedy};
      }
hours_to_show: 8
defaults:
  entity:
    line:
      width: 2
  yaxes:
    fixedrange: true
```

When I use -1, the bar is very narrow, when I use -2, I get 2 bars. Then I just reset 1 bar to zero.
Note that I do not use the statistics.

**Comment by dbuezas** [comment]
I think the new feature https://github.com/dbuezas/lovelace-plotly-graph-card#extend_to_present would help you.
Please reopen if still unsolved :)
