### ISSUE TITLE
auto period determination not intuitive  when combined with range buttons 

### ISSUE THREAD

**Issue by netweaver1970** [dbuezas/lovelace-plotly-graph-card#149]
1st: 36 months using the range button. Screen only half filled because data is only present for the last 17 months. The ‘group by’ period is set to months, as I wanted and have set in the YAML config
![image](https://user-images.githubusercontent.com/18028618/202117079-60cbebc0-80e8-4f0c-ad28-52672f8cd253.png)
 

2nd: Add previously disabled outside temperature, Press autoscale button. X and Y axis got properly scaled, it takes a long time for the redraw. But the ‘group by’ seems to have gone from months to weeks. 
Basically, it seems to take the date range it actually has data for and then applies its internal rules for the ‘group by’ determination, while it should take the previously active ‘group by’ setting, at least that's my use case.

I don’t know how to prevent this behaviour and still make your normal use case work… 
Maybe just make it configurable with an option, so the autoscale function can either use it’s internal ‘group by’ logic based on the time range shown, or in the other (my use case for these graphs), just reuse the ‘group by’ already in use.
 
![image](https://user-images.githubusercontent.com/18028618/202117144-8a86b3da-acdd-4f0d-aa87-f4f1519ae232.png)

3rd: After zooming out using mouse wheel, one graph, the solid red Living room Humidity on, the ‘group by’ stays on week level, while the majority of the graphs go to (as expected) month level.
And the Living room Abs. Humidly is not calculated/shown for the full time range. 
Also, the Living room values themselves seem to be incorrect (compare to my 1st case above). Probably linked to the fact the Living room humidity values are on the wrong ‘group by’ level. 
![image](https://user-images.githubusercontent.com/18028618/202117209-35be293a-33cd-4286-8b75-5890f15dbd7b.png)

**Comment by dbuezas** [comment]
Hi 👋 
For (1 and 2), the way auto period works is by measuring the range visible in the x-axis. The buttons at the top change that so they also change the period. The same happens when you autoscale (the xaxis range changes) At the moment there is no dedicated UI to change the period alone.

Do you get any exceptions in the console for (3)? It looks like home assistant isn't returning the data

**Comment by netweaver1970** [comment]
for 1 and 2, if there was a configurable switch in the YAML, where one could disable the built-in auto period determination ONLY when pressing the  'autoscale' button, and in that case just keep the previous grouping. 
Then it would allow more end-user controlled results, if people want that.

Maybe additionally a GUI enhancement (eg. user selectable grouping buttons) would also help. Similar to the ranges buttons. But not the MVP, more a bling/bling request, when you have some more time and no clue what to do (if ever happens??) ...

for 3, I didn't see any any visible error. But I'll try to reproduce and open the Dev tools, poke around there to see if I can find an error somewhere.

**Comment by dbuezas** [comment]
None is related to this card. If you scroll up do you see anything with the file "plotly-graph-card.js" (at the far right)?

**Comment by netweaver1970** [comment]
yes I do, when I go look for the right js file ...
![image](https://user-images.githubusercontent.com/18028618/202497250-4eecc02e-bbe7-461c-b8a1-4a347784ef1e.png)

**Comment by dbuezas** [comment]
Those are from when you were editing the card. Please reload the page, try to reproduce this failure without editing the config, and then check the console :)

**Comment by dbuezas** [comment]
closing as stale. Feel free to reopen if you gained new insights
