### ISSUE TITLE
Access to entity attributes in lambdas appear to have broken

### ISSUE THREAD

**Issue by CKerswell** [dbuezas/lovelace-plotly-graph-card#152]
Hi,

I had a set of graphs working that shows the current temp, setpoint and heat request for a given room.
To indicate when heat is being requested, the area under the current temperature was shaded, something like this:
![image](https://user-images.githubusercontent.com/70297519/202825834-49e16f4e-569c-43a1-a024-91294856890f.png)

However, I was running HA and plotly versions that were a few months old, so I decided to upgrade.... now I get this:
![image](https://user-images.githubusercontent.com/70297519/202825784-813c1a75-14db-4c61-a88c-29cca9cb2d1f.png)

If I change the following line:
          `result.y.push(+entity[i].attributes.current_temperature)`
to
          `result.y.push(30)`
I see this:
![image](https://user-images.githubusercontent.com/70297519/202825935-9b87aaf5-7a29-4bb3-92ad-0ea444c3b7aa.png)

So my thinking is that the fundamental logic is still working, but that `+entity[i].attributes.current_temperature` is no longer returning a valid value.

Am I doing something wrong that kinda worked before but is no longer supported, or is it a new-ish bug??!

YAML config:
```
type: custom:plotly-graph
entities:
  - entity: climate.loungetrv_climate::current_temperature
  - entity: climate.loungetrv_climate::temperature
  - entity: climate.loungetrv_climate
    fill: tozeroy
    line:
      color: red
      width: 0
    lambda: |-
      (ys, xs, entity) => {
      const result = {x:[], y:[]}
      for (let i = 0; i < ys.length; i++) {
        if (ys[i] == 'heat') {
          result.y.push(+entity[i].attributes.current_temperature)
        }
        else { 
          result.y.push(10)
        }
        result.x.push(+xs[i])
      }
      return result;
      }
hours_to_show: 24
```

**Comment by dbuezas** [comment]
I'll take a look soon. It may well be a bug, sorry for that.
The contribuitors and I have changed and added a lot of things lately, and only now started to gather test yamls to avoid against mistakes.

I'll let you know when I find the issue

**Comment by CKerswell** [comment]
Thanks, no need to be sorry, you are doing great work!

An interesting development this evening that I can't understand...

On my wall tablet using Fully browser, it was working fine!
![20221121_223612](https://user-images.githubusercontent.com/70297519/203173205-2602b916-1579-464d-8b35-6f0a2170239e.jpg)

But at the same time, in Chrome on the laptop, the same graph on the same dashboard looked like this:
![20221121_223714](https://user-images.githubusercontent.com/70297519/203173209-7f37510a-f906-4bed-8841-de09cdc91142.jpg)

**Comment by dbuezas** [comment]
Ok, the issue is that the last trace doesn't fetch the attributes because it's not expecting you to use them.
```yaml
type: custom:plotly-graph
entities:
  - entity: climate.loungetrv_climate
    attribute: current_temperature # new cleaner api
  - entity: climate.loungetrv_climate
    attribute: temperature
  - entity: climate.loungetrv_climate
    attribute: current_temperature
    fill: tozeroy
    line:
      color: red
      width: 0
    lambda: |-
      (ys, xs, entity) => ys.map((y, i) =>
        (entity[i].state == 'heat') ? y : 10
      )
hours_to_show: 24
```

Alternatively, you can force `minimal_response: false` and `significant_changes_only: true`, more here https://github.com/dbuezas/lovelace-plotly-graph-card#minimal_response


Pro tip:
You can debug lambdas by calling `console.log(ys,xs,entity)` and opening the chrome dev tools. You can even add `debugger` and (if you have devtools open) it will stop execution for you to look at variables and whatnot.

This should solve your issue, but feel free to reopen it if it doesn't :)

**Comment by dbuezas** [comment]
As to why it works sometimes in some devices, no idea

**Comment by CKerswell** [comment]
Thanks for the update and the debugger tip!

So, when I used your code, I had intermittent results - sometimes fine, sometimes it seemed the lambda didn't run and just the original value was shown:

![image](https://user-images.githubusercontent.com/70297519/210021973-2cd782f7-c639-4617-86b1-d409e2f0f45c.png)

Upon further investigation, sometimes it seems the entity array is one less than the ys and xs arrays.
When this is the case, it seems to break the lambda.

I expanded the code back to my original long-hand code as I still need to get my head around arrow functions and using maps and various other shorthand!


The following code is intermittent:

```
type: custom:plotly-graph
entities:
  - entity: climate.loungetrv_climate
    attribute: current_temperature
  - entity: climate.loungetrv_climate
    attribute: temperature
  - entity: climate.loungetrv_climate
    attribute: current_temperature
    fill: tozeroy
    line:
      color: red
      width: 0
    lambda: |-
      (ys, xs, entity) => {
      const result = {x:[], y:[]}
      for (let i = 0; i < ys.length; i++) {
        if (entity[i].state == 'heat') {
          result.y.push(+ys[i])
        }
        else { 
          result.y.push(0)
        }
        result.x.push(+xs[i])
      }

      return result;
      }
hours_to_show: 48
```

It returns 323 items for the `entity` array, but 324 for `ys` and `xs`:
![image](https://user-images.githubusercontent.com/70297519/210022169-7523817f-4f49-44ce-8530-1fc5fd7924f9.png)

If I limit the for loop to 320, then the above code works reliably, but obviously that's quite hacky!

---

The next step I took was to ditch the `ys` and `xs` arrays and just use the `entity` array, because in my case all the info was available:

```
type: custom:plotly-graph
entities:
  - entity: climate.loungetrv_climate
    attribute: current_temperature
  - entity: climate.loungetrv_climate
    attribute: temperature
  - entity: climate.loungetrv_climate
    attribute: current_temperature
    fill: tozeroy
    line:
      color: red
      width: 0
    lambda: |-
      (ys, xs,entity) => {

      const result = {x:[], y:[]}
      for (let i = 0; i < entity.length; i++) {
        if (entity[i].state == 'heat') {
          result.y.push(+entity[i].value)
        }
        else { 
          result.y.push(0)
        }
        result.x.push((+entity[i].timestamp))
      }
      //debugger;
      return result;
      }
hours_to_show: 48
```

This seems to work reliably.

I've not really got to the bottom of why the `xs` and `ys` arrays are of different length to `entity`, but that at least seems to be the root cause here.

**Comment by CKerswell** [comment]
Upon further investigation, I never seem to get the latest `entity` value:

![image](https://user-images.githubusercontent.com/70297519/210022911-82cbbe58-1962-44e7-83e8-de4a7a41a840.png)

Sometimes I seem to get a load of earlier `entity` values, (one example I had 29 `entity` values but only 6 `xs` and `ys`).  In this case, all of the values in `xs` and `ys` were stored in `entity` except the latest one, plus `entity` contained a load of earlier values too.

**Comment by dbuezas** [comment]
Oh I see, there's an issue with extend_to_present. It only extends xs and ys. I'll fix that. In the meantime it's good you use the third parameter.
I'm working on new approach to lambdas. It's not final yet, but you can get an idea here https://github.com/dbuezas/lovelace-plotly-graph-card/blob/f055482483d5993027df95442f38a04190bd8b85/readme.md#filters
Do drop feedback in the pr if you have some :)

**Comment by dbuezas** [comment]
This is what your lambda will soon become:
```yaml
- entity: climate.loungetrv_climate
  attribute: current_temperature # an attribute must be set to ensure attributes are fetched.
  filters:
    - map_y_numbers: state.state === "heat" ? y : 0
```

preview: https://github.com/dbuezas/lovelace-plotly-graph-card/blob/feat/add-esphome-style-filters/readme.md#using-state-attributes

**Comment by dbuezas** [comment]
The latest version solves this issue.
I strongly encourage you to switch to filters which allow for a much cleaner yaml (also, lambdas are not maintained anymore 😁 )
