### ISSUE TITLE
Make `offset` work in entities default config

### ISSUE THREAD

**Issue by FrnchFrgg** [dbuezas/lovelace-plotly-graph-card#156]
The way `offset` is fetched, it ignores any value set in the `default.entities` object. But having the same offset on every entity does not give the same result than using a global `offset`, and is thus worthwhile to have.

**Comment by dbuezas** [comment]
Again? 
Oh yes, it shouldn't be entityIn: https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/plotly-graph-card.ts#L409

I keep making different variations of the same mistake.

Note to self: put the defaults merging logic in a different function and hide the unmerged entity variable from the scope after merging
