### ISSUE TITLE
bug in line when the graph is dragged and shape:linear

### ISSUE THREAD

**Issue by perropinto** [dbuezas/lovelace-plotly-graph-card#158]
After version 1.5.3 , this happens when the graph is dragged. Only occurs when "shape:linear". How can I install version 1.5.3 while this bug can't be fixed?  (I attached image below)  this is my configuration:

**type: custom:plotly-graph
entities:
  - entity: sensor.switch1local_voltaje
    fill: tozeroy
    line:
      color: darkblue
      dash: line
      width: 0.7
      shape: linear
  - entity: sensor.wifi_interruptor_de_carril_din_con_medicion_voltaje
    fill: tozeroy
    line:
      color: ORANGE
      dash: line
      width: 0.7
      shape: linear
layout:
  plot_bgcolor: white
  height: 400
  config: null
  hours_to_show: 3
  refresh_interval: 30
  yaxis:
    autorange: match
    range:
      - 220
      - 250
    ticksuffix: V.
  xaxis:
    rangeselector:
      'y': 1.2
      buttons:
        - count: 10
          step: second
        - count: 1
          step: minute
        - count: 30
          step: minute
        - count: 1
          step: hour
        - count: 3
          step: hour
        - count: 1
          step: day
        - count: 7
          step: day**

![imagen](https://user-images.githubusercontent.com/50021494/203685230-4e5e3ef6-9a98-4efc-ba6e-23fe3ac7d1b8.png)

**Comment by perropinto** [comment]
addition:  It happens if you first zoom the graph, and then drag it.

**Comment by netweaver1970** [comment]
Thanks for following this up. I'm on holiday for 2 weeks and significant other doesn't appreciate too much laptop work...

**Comment by dbuezas** [comment]
https://github.com/plotly/plotly.js/issues/6407
