### ISSUE TITLE
show value in legend

### ISSUE THREAD

**Issue by miljbee** [dbuezas/lovelace-plotly-graph-card#199]
Hello,

It would be great to be able to display the last value in the legend, this would solve this problem:
![image](https://user-images.githubusercontent.com/637997/214397929-347caf67-a831-40b0-afe6-7be34eb826f1.png)

Thanks !

**Comment by dbuezas** [comment]
I'm on it, arbitrary functions everywhere :)

**Comment by dbuezas** [comment]
Will be covered by #200, #130

**Comment by dbuezas** [comment]
Closed by the release of v3.0.0
