### ISSUE TITLE
Make height configurable

### ISSUE THREAD

**Issue by storeman** [dbuezas/lovelace-plotly-graph-card#27]
Would it be possible to create a configurable height so one could see more detail, like the mini-graph-card: 
https://github.com/kalkih/mini-graph-card

This would be a lot more readable if I could adjust the height:
![afbeelding](https://user-images.githubusercontent.com/81527/153570190-0df0152a-13b6-47d7-86fe-c5ac3905abb0.png)

**Comment by dbuezas** [comment]
You have 2 options:
* Make the card take the whole panel (edit the whole tab with the pencil icon)
* Set the height:
```yaml
layout:
  height: 800
```

**Comment by storeman** [comment]
I'm sorry I did not find that in the docs. Thanks!
