### ISSUE TITLE
Ecobee Data Issue

### ISSUE THREAD

**Issue by Ic3Nine** [dbuezas/lovelace-plotly-graph-card#287]
**Describe the bug**
 I am having an issue with one entity climate.ecobee that in plotly it shows just one data point (the call for heat/cold) but in the history graph it shows 3 separate data points: target temp, current temp, heating/cooling.

**Screenshots**
plotly : https://i.imgur.com/ScFqady.png
built-in : https://i.imgur.com/GVyjcBv.png

**yaml**
```
type: custom:plotly-graph
entities:
  - entity: climate.ecobee
hours_to_show: 24
refresh_interval: 10
title: Pltoly
```
```
type: history-graph
entities:
  - entity: climate.ecobee
title: Built-In
```

**Additional context**
Wondering if I am missing something in plotly to be able to see the same data.  I've gone through the docs without any luck.  Anyone else here with an ecobee that might have gone through the same thing?

**Comment by dbuezas** [comment]
Yes, see the attributes section
