### ISSUE TITLE
Feature request: support for daily / hourly values

### ISSUE THREAD

**Issue by tomlevels** [dbuezas/lovelace-plotly-graph-card#32]
I have some sensors for hourly and daily values that increase till the next hour/day and then reset. It is now not very easy to create a graph of the maximum of these hourly/daily values (a bar chart for example)
For example I have this graph (created in another graph library, but this does not allow me to scroll easily):
![image](https://user-images.githubusercontent.com/3691709/158564962-ed0daf53-dcfa-4d61-a752-b43ec64fd935.png)

This is based on this sensor:
![image](https://user-images.githubusercontent.com/3691709/158565320-f5797c66-821a-4f7f-9f29-0cb21a24036d.png)

**Comment by dbuezas** [comment]
You want to plot the maximum values for each hour, right?
You can use lambdas for that.
Do you code?

**Comment by tomlevels** [comment]
Yes, I want to plot the maximum values for each hour.
I assumed I could use lambdas for that and if I try hard, I might be able to create that code. The point is that a lot of people do not know how to code this and it would be nice to incorporate some basic functionality like this in an easy way, so more people can easily use this component.

**Comment by dbuezas** [comment]
Hi Tom. That's an interesting idea.
I could provide a list of pre-made functions to pass to the "lambda" field.
```yaml
  - entity: sensor.temperature
    lambda: tranformations.max("1 hour") 
```

In the meanwhile, for your particular case it may be better to keep only the datapoints with a negative derivative:
```yaml
- entity: sensor.solar_production_hourly
  name: lambda
  lambda: |-
      (ys, xs) => {
        const result = {x:[], y:[]};
        for (let i = 0; i < ys.length - 1; i++) {
          if (ys[i+1] < ys[i]){
            // keep this one as the next one is the reset point (derivative is negative)
            result.x.push(xs[i]);
            result.y.push(ys[i]);
          }
        }
        // add the last one to keep the "now" state in the plot
        result.x.push(xs[xs.length-1]);
        result.y.push(ys[ys.length-1]);
        return result;
      }
 ```

**Comment by tomlevels** [comment]
I think a list of pre-made functions would be very useful for a lot of people with limited or no programming skills. Also thanks for the example code, it is already working great.
