### ISSUE TITLE
Thousands separator inconsistent

### ISSUE THREAD

**Issue by JvdMaat** [dbuezas/lovelace-plotly-graph-card#37]
I have a graph that has 4 digit numbers that are sometimes whole and sometimes have a decimal.
When hovering over the numbers, if it's a fraction, it will have a comma for the thousands separator, when it's a whole number, there is no separator:
5236
6,241.5
Verified the data in Home Assistant History, and it consistently adds the thousands comma separator.

**Comment by dbuezas** [comment]
D3 decides how to present numbers but you can override everything. Via a hover template: https://plotly.com/javascript/hover-text-and-formatting/#hovertemplate

Let me know is you succeed :)

One extra caveat is that numbers are represented as strings (in case you are plotting categorical values). This may affect how they are shown. To force them to be numbers, you can add:
```yaml
entities:
   - entity: sensor.mysensor
     lambda: ys => ys.map(y => +y)
```
