### ISSUE TITLE
To be able to detect whether a trace is displayed (enabled or disabled in the legend)

### ISSUE THREAD

**Issue by jnxxx** [dbuezas/lovelace-plotly-graph-card#387]
**Describe the solution you'd like**

I am using an expression to calculate a range for a y-axis, because I need to exclude a trace.
I use `getFromConfig(`entities`)` to get the traces, then find min and max for the desired traces.

```yaml
layout:
  yaxis:
    visible: true
    fixedrange: false
    autorange: false
    range: |
      $ex {
        var ary = [];
        const entities = getFromConfig(`entities`);
        for(var i = 0; i < entities.length; i++) {
          if (['Current', 'Target', 'Floor (trend)', 'Sensor'].includes(entities[i].name)) {
            ary = ary.concat(entities[i].y);
          }
        }

        var min = Math.min( ...(ary) );
        var max = Math.max( ...(ary) );

        return [min-0.1, max];
      }

```

This is working fine.
But it would be nice if I could also detect which traces have been hidden, by clicking it in the legend. And thereby being able to adjust the range to zoom into the traces that are shown.

For example a boolean like: `entities[i].enabled` or `entities[i].visible`.

**Comment by dbuezas** [comment]
I just realised this may be possible, I'm passing an array of visibility to the yaml interpreter to disable fetching for invisible traces.
https://github.com/dbuezas/lovelace-plotly-graph-card/blob/master/src/plotly-graph-card.ts#L377

Try `const is_entity_visible = get('fetch_mask')[i]` (get is a shorter alias of getFromConfig)

**Comment by jnxxx** [comment]
It is working.
Thank you.

**Comment by jnxxx** [comment]
I ran into a slight issue though.
It seems as if `get('fetch_mask')` is not always initialized.
For example if I refresh the hosting page or use it in a browser_mod popup, it returns all false.

For now I made the following workaround:
```javascript
        const entities = get('entities');
        var masks = get('fetch_mask');
        if (masks.every((val) => val == false)) {
          for(var i = 0; i < entities.length; i++) {
            masks[i] = !entities[i].visible && entities[i].visible != "legendonly";
          }
        }
```
