### ISSUE TITLE
RGBA cannot be used as a line color

### ISSUE THREAD

**Issue by ajavibp** [dbuezas/lovelace-plotly-graph-card#416]
**Describe the bug**
If color is specified in RGBA format, transparency has no effect

entities:
  - entity: sensor.inverter_active_power
    name: $ex "Producción-Relleno"
    showlegend: false
    line:
      color: rgba(230,255,230,0) 

Using color: rgba(230,255,230,1) obtain exactly the same color. There is no transparency effect.

**Comment by dbuezas** [comment]
Use opacity instead on the entity instead

**Comment by ajavibp** [comment]
Thank you. That option is not in the card documentation, so I was unaware of it.
In any case, does it also affect the filling? It just seems to me that it doesn't work correctly with the fill (it does with the line).

**Comment by dbuezas** [comment]
I think it does. Google "how to change line transparency in plotlyjs" or check out their docs.
Line colors are a native feature of plotly itself, this card handles integration with home assistant, filters, $fn, and other accessories :)
