### ISSUE TITLE
Not Available on HACS

### ISSUE THREAD

**Issue by firebird71** [dbuezas/lovelace-plotly-graph-card#421]
I was doing  updates in HACS and it removed this card.
then I tried searching for the card to add it again and it showed 'No repositories found matching your filter'.
I tried to add a Custom repository and if failed saying it already existed.

![Screenshot from 2024-05-19 12-43-49](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/3182618/33307fe4-dc57-4f36-94e6-ed572fd1ae92)

> Home Assistant Community Store
> Integration version:	1.34.0
> Frontend version:	20220906112053
> Repositories:	1392
> Downloaded repositories:	29
> 

Any ideas on what happened

**Comment by dbuezas** [comment]
Are you sure you searched in the frontend tab and not the integrations one?

**Comment by firebird71** [comment]
Yes, I actually tried both just to make sure. When HACS removed it it said something like This repository has been marked archived or something like that, I can't remember exactly.  I was doing a few updates at the time along with other things around the house being the first nice day in a week or so.

**Comment by dbuezas** [comment]
It's still in the lists. I removed it from hacs to check and I see it just fine:
<img width="729" alt="image" src="https://github.com/dbuezas/lovelace-plotly-graph-card/assets/777196/1314c1a5-e433-4fec-9208-beedf8062009">

https://github.com/hacs/default/blob/master/plugin#L79

**Comment by firebird71** [comment]
Ok maybe its a problem with HACS.
![Screenshot from 2024-05-20 08-28-23](https://github.com/dbuezas/lovelace-plotly-graph-card/assets/3182618/7f13ca8d-95f1-432a-bbe3-b1439a798d96)
I was just trying to add it because I couldn't find it.

**Comment by firebird71** [comment]
Ok, I don't know what was going on but I turned on HACS logging and did a full system reboot and everything is working now maybe all the updates and just a HA restart caused the problem sorry for wasting your time.
