### ISSUE TITLE
addition of longterm data in the graphs

### ISSUE THREAD

**Issue by SustainableBlueDuck** [dbuezas/lovelace-plotly-graph-card#459]
**Describe the solution you'd like**
Long longterm data alongside shorterm data

**Additional context**
This was a feature of the 'original' [history-explorer-card ](https://github.com/alexarch21/history-explorer-card) which was alvailable on HACS. The most recent fork of this card that I know of is this [one](https://github.com/SpangleLabs/history-explorer-card).
The card is removed from my HA instance, so I don't have a image to share. The longterm data would show up as a somewhat lighter colour to indicate it is longterm data.

**Comment by dbuezas** [comment]
See https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/415
