### ISSUE TITLE
Error on tizen, family hub fridge, graph doesn't render

### ISSUE THREAD

**Issue by atv2016** [dbuezas/lovelace-plotly-graph-card#49]
For some reason it says can't find custom plotly graph element anymore in the browser.
Not sure if it ever worked.

**Comment by dbuezas** [comment]
Hello,
what browser are you using?
Would you open the devtools and make a screenshot of any error in it?

**Comment by atv2016** [comment]
Not sure, it's tizen 6.0 running on a Samsung Family hub :-)
webkit ?
![IMG_6287](https://user-images.githubusercontent.com/16917203/172146558-6d0ca6cd-d9f8-4590-be2f-437fa3c85b39.jpg)
![IMG_6289](https://user-images.githubusercontent.com/16917203/172146575-e8d631a5-8728-4611-b2cf-0338b1c536b9.jpg)

**Comment by atv2016** [comment]
This seems related:
https://community.home-assistant.io/t/samsung-family-hub-tizen-browser-custom-element-does-not-exist/186059

**Comment by dbuezas** [comment]
Ok, the card is not loaded at all.
If you did install it through HACS, the this is not not specific to this card.
Wish you luck!

**Comment by atv2016** [comment]
So..you're saying this is because of the browser?

**Comment by dbuezas** [comment]
Yes, the Library isn't loading at all.
If you open the developer console in the browser and can screenshot any error there, it may be of help
