### ISSUE TITLE
Feature Request: Preprocess Data

### ISSUE THREAD

**Issue by lein1013** [dbuezas/lovelace-plotly-graph-card#5]
Would it be possible to enable a normaliz function on the data on the latest value? (or on the first/average value of the selected timeframe 1day, 1 week,..)
e.g. if you have a 5 stock charts with a large difference in their stock value, this would allow to compare the trends of the stocks

**Comment by dbuezas** [comment]
Interesting idea.
Can you post examples as you imagine the configuration would look like?

The other two alternatives I see are:
* To guide people towards the [statistics sensor](https://www.home-assistant.io/integrations/statistics/)
* To allow for an arbitrary JavaScript mapping function

But I do like the convince your idea would bring

**Comment by lein1013** [comment]
Let's take the normalization on the latest value and assume to have N lines (e.g. different stocks) in the chart. Then I'd like to see all lines in the chart ending up to 100%
n=1,..,N
values[n][:] = values[n][:]/values[n][-1]
by that kind of normalizsation you can see the trend of the stocks, independent from the selected timeframe (4h, 1d, 1w)
alternatively we can also normalize with the first value (values[n][:]/values[n][0]), then we see the trend based on the selected timeframe -> how much percent did the stock perform better than the other one

allowing mapping functions sounds interessting

**Comment by dbuezas** [comment]
I'm thinking of something like this:

### example of normalisation wrt to last 
```yaml
type: custom:plotly-graph
entities:
  - entity: sensor.my_sensor
     lambda: |-
        (y) => y.map(v => v/y[y.length-1])
```
### example of normalisation wrt to first fetched value
```yaml
  - entity: sensor.my_sensor
     lambda: |-
        (y) => y.map(v => v/y[0])
```
---

So basically a js function that receives all the data for that entity, and you can do whatever you want. The problem is that the unit_of_measurement would also need to be tweakable.

---


Here some more examples, including `unit_of_measurement` (to show along the y axis and in the tooltips).
### example of accumulated value
```yaml
  - entity: sensor.my_sensor
     unit_of_measurement: "total pulses"
     lambda: |-
        (y) => {
          let accumulator = 0;
            return y.map(v => accumulator + v)
        }
```
### example of derivative
```yaml
  - entity: sensor.my_sensor
     unit_of_measurement: "pulses / second"
     lambda: |-
        (y, x) => {
          let last = {
            date: new Date(),
            value: 0,
          }
          return y.map((value, index) => {
            const date = x[index];
            const dateDelta = date - last.date;
            accumulator += (value - last.value) / dateDelta;
            last = { date, value };
            return accumulator;
          })
        }
```
### example of right hand riemann integration
```yaml
  - entity: sensor.my_sensor
     unit_of_measurement: "kWh"
     lambda: |-
        (y, x) => {
          let accumulator = 0;
          let last = {
            date: new Date(),
            value: 0,
          }
          return y.map((value, index) => {
            const date = x[index]
            const dateDelta = date - last.date;
            accumulator += last.value * dateDelta;
            last = { date, value };
            return accumulator;
          })
        }
```

---

What do you think? 

Regarding normalising against the first value, you should consider that the "first value" will be just the 1st *known* value, which will change if you scroll the plot and older data is fetched

**Comment by lein1013** [comment]
Looks great!
With these examples, it looks like a real nice playground to experiment with visualisations directly in the lovelace config!

**Comment by dbuezas** [comment]
Cool, then I'll give it a go tomorrow :)
Thanks for the cool ideas!
I use my own hardcoded "hacked" version to do things like these.
With your feedback, I think we nailed a configurable way 👍

**Comment by dbuezas** [comment]
@lein1013 done in v0.5.0!
try it out and let me know if it works as you needed :)

**Comment by lein1013** [comment]
Thanks for implementation! 
Works as specified :-)
