### ISSUE TITLE
feature request: annotations?

### ISSUE THREAD

**Issue by atv2016** [dbuezas/lovelace-plotly-graph-card#50]
would be nice to have

**Comment by dbuezas** [comment]
Hey,
could you doodle you mean in a piece of paper?

**Comment by atv2016** [comment]
I mean like put in a comment next to a certain event in the graph, similar to what grafana has.

**Comment by dbuezas** [comment]
I'm not a grafana user, can you post a screenshot?

**Comment by dbuezas** [comment]
Closing as stale
