### ISSUE TITLE
Stacking Multiple Sensors on one grap

### ISSUE THREAD

**Issue by AdamSoddo** [dbuezas/lovelace-plotly-graph-card#52]
I am having some trouble getting my graph to look right.  I am stacking 3 power monitoring sensors (phase 1,2,3) on one graph. The data from the sensors has a DateTime with ms precision.  Because of this, the data do not all fall at the same time but instead get drawn at their own interval on the graph.  I'm using the stackgroup function to put them all in a single stack and plot them on top of each other.
What seems to happen is that the system is looking at the precise time stamp instead and stacking only data that has the same time stamp to the millisecond. If the timestamps are different (even by millisconds) it inserts a 0%{customdata.unit_of_measurement} for the value of the other sensors.  This results in add short spikes or gaps in the data. 

Could I tell plotly if there is no specific data point for that time stamp to keep using the last datapoint from the same sensor? or can I re do the graph and align it by minute instead of second or millisecond?
![Capture](https://user-images.githubusercontent.com/61877648/173596273-2bc6ebb8-9ffa-4a27-9857-ae9eb954a35c.JPG)
![Capture2](https://user-images.githubusercontent.com/61877648/173596949-5276585f-2e52-4f61-8fcb-8fffa86bc0c4.JPG)

**Comment by dbuezas** [comment]
You are in luck: 
https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/35

Btw, for Q&A, use the discussions instead :)
