### ISSUE TITLE
Customization: hovertemplate behavior

### ISSUE THREAD

**Issue by eagleco** [dbuezas/lovelace-plotly-graph-card#53]
I'm trying to customize hovertemplate but whatever I set seems to get `%{customdata.name} : ` added in front of it, am I missing a configuration option or is there some other way to prevent this? See yellow and red boxes below for an example

![image](https://user-images.githubusercontent.com/39813792/173933129-1db5e6a2-6df7-4e83-a100-1226c669a820.png)

I poked around a little bit in _plotly-graph-card.ts_ but my js is pretty weak.  I see where the default template is set but can't figure out why the `name :` still gets added when I provide a template?

![image](https://user-images.githubusercontent.com/39813792/173932637-b096574a-35d8-48dd-8359-ca8c44d9e4a0.png)

**Comment by dbuezas** [comment]
This is a limitation of plotly specific to `hovermode: unified`. I updated plotly yesterday so you can try upgrading, but I doubt this changed changed.

The only other option I'm aware of is to use `hoverinfo` instead.

Closing it now, but please do post your result if you succeed with `hoverinfo` :)
