### ISSUE TITLE
Error “Custom element doesn’t exist: plotly-graph” on older versions of iPad

### ISSUE THREAD

**Issue by A-E-M-Wiz** [dbuezas/lovelace-plotly-graph-card#63]
**Error Description**
The card cannot render on older versions of the iPad, and returns error “Custom element doesn’t exist: plotly-graph”. The card works on both PC and Android, so the configuration is correct.

**Setup**
iPad Air (1st gen) running IOS 12.5.4.
Tested and failes on Chrome v 87.0.4280.77, Safari as well as in Home Assistant app v 2022.3.

UA Info Chrome: 
Mozilla/5.0 (iPad; CPU OS 12_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1
UA Info Safari:
Mozilla/5.0 (iPad; CPU OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

**Further info**
There are no errors in the Home Assistant log.

The issue might be related to the following issue and seems to be resolved based on the comments:
https://github.com/AlexxIT/WebRTC/issues/107

**Comment by dbuezas** [comment]
Hi there 👋 
Do you get this when loading HA via the app only or also over these browsers?

**Comment by A-E-M-Wiz** [comment]
Thanks for looking into this.

I get same result on all 3 options (HA app, Safari, and Chrome) when used on the ipad.

**Comment by dbuezas** [comment]
I don't have an iPad so this is a bit of a blind shot:
Please upgrade to 1.3.3-RC and let me know if it works now
(go to HACS/front-end integrations/plotly card/upgrade)

**Comment by A-E-M-Wiz** [comment]
Thanks for looking into it.
Unfortunately, the issue persists. 

I think it might be a very generic issue:
https://community.home-assistant.io/t/custom-cards-not-working/189629

It is actually affecting all cards from HACS.

**Comment by A-E-M-Wiz** [comment]
However, HACS has closed this issue, with the reply that it is up  to the individual card to fix it.

https://github.com/hacs/integration/issues/2814

**Comment by dbuezas** [comment]
Uhm. I see no clue there, but I doubt it is HACS related.
I'll need to see the console to know what the error is.
You could try this: https://blog.chromium.org/2019/03/debugging-websites-in-chrome-for-ios.html?m=1
And then copy&paste errors related to the plotly card.

Also, please open this page in the old ipad: https://plotly.com/javascript/line-and-scatter/ and check if you can see the plots. If you can't, it is plotly itself, and there's nothing I'll be able to do about it. But the plots do work, then this card is fixable :)
It could be that pl

**Comment by dbuezas** [comment]
Alright, that's good.
Can you keep the debugger tab open and reload the other tab with home assistant?

Btw: good call blacking sensitive data!

**Comment by A-E-M-Wiz** [comment]
One step closer :-)

![image](https://user-images.githubusercontent.com/11346733/183516563-748a3ee3-df0f-46aa-a8c4-f86a5adb030b.png)

**Comment by A-E-M-Wiz** [comment]
Hmm, unfortunately, I already tried that. I just tried again to play around with it a bit, but I cannot generate any useful errors in the logs :-/

**Comment by dbuezas** [comment]
Ok, the only option left to get a better console is this one:
https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by JSteunou** [comment]
I had the same issue, just empty your cache or reload without cache.

**Comment by dbuezas** [comment]
Closing this one, let me know if the issue persists.
