### ISSUE TITLE
[Q] Update chart on value change?

### ISSUE THREAD

**Issue by PulsarFX** [dbuezas/lovelace-plotly-graph-card#66]
I'd like to have the chart updated when the sensor value changes, like it is done with the history card. Is this possible? 

If not: is it possible to have buttons to change the update interval, just like the range selector buttons?

**Comment by dbuezas** [comment]
Yes, by using the websockets API.
This will also allow the card to get the long term statistics data.
I'll eventually get to it.
In the meanwhile, you can change the update interval in yaml (see readme) or just move the plot a bit with the mouse to update

**Comment by dbuezas** [comment]
Good news! :)
Websockets weren't necessary, home assistant's frontend already exposes this to the card.
If you want to test the work in progress, here's the PR:
https://github.com/dbuezas/lovelace-plotly-graph-card/pull/114

**Comment by dbuezas** [comment]
Feature available in v1.7.0
(see refresh_interval: auto)
