### ISSUE TITLE
Missing graph sections

### ISSUE THREAD

**Issue by hmax42** [dbuezas/lovelace-plotly-graph-card#69]
Hi
i recently discoverd this card, and i like it very much, but why are there sections in graphs omitted if the value doesn't change.
it looks bad compared to the history-graph, for example:

![image](https://user-images.githubusercontent.com/22865687/188788219-fd9b22f6-0132-46e8-a345-133ecaff1b32.png)
![image](https://user-images.githubusercontent.com/22865687/188788257-c23facb3-4665-4576-908a-01994242200d.png)

or am i missing some parameter? apologies if i do
tonexty and tozeroy are not the solutions i am looking for

**Comment by dbuezas** [comment]
Hi!
This is odd, the discontinuities should only appear when a sensor goes to unavailable, not when it stays constant.

In any case, you could try the solution in #44

**Comment by hmax42** [comment]
thanx for the tipp.
the sensors (ble sensor via esphome) themselves are all filtered with throttle and heartbeat, each 20s, so there should never be an unavailable hole.

this solution did the trick for me
>defaults:
>  entity:
>    lambda: |-
>      (ys, xs)=>({
>        y:ys.filter(y=>!Number.isNaN(parseFloat(y))),
>        x:xs.filter((x,i)=>!Number.isNaN(parseFloat(ys[i]))),
>      })
