### ISSUE TITLE
Feature request: pop-up à la sensor card

### ISSUE THREAD

**Issue by bennop** [dbuezas/lovelace-plotly-graph-card#72]
I really like to use plotly graphs but do miss the full size pop-ups that sensor cards provide and think this would be a great feature for plotly graph cards, too

**Comment by dbuezas** [comment]
Hey bennop,
can you send a screenshot or link of what you mean?

**Comment by bennop** [comment]
Sure!

Clicking on the temperature sensor card (➊) I get the pop-up shown in the first screenshot.


BTW, this seems to work for any basic card representing a sensor, even binary ones


Clicking into the headline of that pop-up (➋) expands it to an almost fullscreen (well, full-window, of course) version of itself providing a much more detailed view:

**Comment by bennop** [comment]
<img width="640" alt="Screenshot 2022-09-19 at 10 39 23" src="https://user-images.githubusercontent.com/5919157/190989847-26e08383-0476-445d-813d-6793808acf0a.png">

**Comment by bennop** [comment]
<img width="640" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/5919157/190989939-594f9338-1ec9-4e60-876a-536a260eede7.png">

**Comment by bennop** [comment]
<img width="640" alt="Screenshot 2022-09-19 at 10 39 38" src="https://user-images.githubusercontent.com/5919157/190989981-95570cf6-0bb0-46cb-94fc-aaaa5137d8be.png">

**Comment by dbuezas** [comment]
Ohhh I get it now, I like that!
 I think there's a way to attach click handlers to the individual traces, and then open the sensor cards. I'll give it a try next time.
Thanks for the idea!

**Comment by bennop** [comment]
Glad you like it, too!

What you mention seems an easy route - hope it is feasible … 

	Benno

**Comment by dbuezas** [comment]
So, I gave it a try but unfortunately I couldn't make plotly's  click event listeners to tell me what was clicked.

**Comment by bennop** [comment]
Thank you for trying!

**Comment by dbuezas** [comment]
I'll close it as i see no way of implementing it at the moment. Thanks for the report!

**Comment by dbuezas** [comment]
https://plotly.com/javascript/reference/layout/#layout-click
Accidentally found this, which may make it possible to implement this feature

**Comment by dbuezas** [comment]
Closed by the release of v3.0.0. Example in readme
