### ISSUE TITLE
Layout setting become persistent ?

### ISSUE THREAD

**Issue by Masterz69** [dbuezas/lovelace-plotly-graph-card#73]
Have one plotty card configured for right Y-axis:
```
layout:
  margin:
    r: 50
```
![image](https://user-images.githubusercontent.com/15225823/190920975-1d01767c-0bb8-446c-bb04-fb2c2b252acd.png)

Issue is: after switching to other lovelaces this setting become applied on cards where NOT configured !!!
![image](https://user-images.githubusercontent.com/15225823/190921003-d1886f63-6421-4f0d-8e36-eecfd4314cb4.png)

Before card with ```layout``` configured opened once card with no right ```margin``` looks as expected:
![image](https://user-images.githubusercontent.com/15225823/190921067-9d999039-f75b-48a7-88aa-96c0128a9ebb.png)

**Comment by dbuezas** [comment]
Oh wow, I think HA is recycling the components. I'll take a look soon.

**Comment by dbuezas** [comment]
Oh, and thanks for rising an issue

**Comment by dbuezas** [comment]
This should be fixed now, can you confirm?
Please feel free to reopen the issue if the bug is still there

**Comment by Masterz69** [comment]
> This should be fixed now, can you confirm?

So far I checked - fixed.
Thank You very much.
