### ISSUE TITLE
Support for nested attributes

### ISSUE THREAD

**Issue by thomaschn** [dbuezas/lovelace-plotly-graph-card#74]
As described [here](https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/51), there is currently no way to access nested attributes. However, this would be incredibly useful for weather forecast data.

**Comment by dbuezas** [comment]
Closing as there is now a workaround inside #51. Home assistant doesn't expose these nested attributes in their REST api, but for the specific case of forecasts, only the last datapoint is important, and that one is now (since v1.7.0) extracted by different means.
