### ISSUE TITLE
Conditional date formatting in time axis

### ISSUE THREAD

**Issue by Bascht74** [dbuezas/lovelace-plotly-graph-card#85]
Hi, 

Could the date be shown in the time axis as the normal historiy graph?
In the history graph the date is shown instead of "00:00" which is kind of nice as it saves one line. 
![image](https://user-images.githubusercontent.com/66269310/197834160-56f1cae3-c7ec-4fb6-9e9f-eaaf13ee5750.png)

Thx for your great work, 

Sebastian

**Comment by dbuezas** [comment]
Hey Sebastian!
All three are very good points. I'd indeed appreciate it if you did 3 entries, so I can tackle them independently :)

**Comment by Bascht74** [comment]
> Hey Sebastian! All three are very good points. I'd indeed appreciate it if you did 3 entries, so I can tackle them independently :)

Done :-) 

Thx again for fixing the title formatting.

Sebastian

**Comment by dbuezas** [comment]
If you want to give it a try yourself, you can find a good template and other props from here https://plotly.com/javascript/reference/#layout-xaxis-tickformat
These can be tested directly from the yaml

**Comment by dbuezas** [comment]
I investigated a bit and now think this won't work.
I see only two options:
* Modifying Plotly's source code and change their date formatter like [this developer](https://github.com/plotly/plotly.js/issues/99#issuecomment-244293965)
* Implementing the tick algorithm from scratch and passing the array of ticks to show directly, like [this](https://plotly.com/javascript/tick-formatting/#tickmode---array)

The downside of implementing the algorithm from scratch is that it will limit how configurable things are. Also, I think it is not a trivial task (except if one finds a good library, potentially a d3 formatter)

**Comment by dbuezas** [comment]
I just re-read the plotly docs and I think this is indeed possible via configuration. It's interesting that I didn't find code in stackoverflow.

**Comment by dbuezas** [comment]
After some trial and error, I got this, but it is too ugly to use.
Help welcomed :) 
![custom x axis formatting](https://user-images.githubusercontent.com/777196/198838075-98e6a930-db84-4f07-8eee-09a3790c1442.gif)

**Comment by dbuezas** [comment]
Here's an example using tickformatstops, but there seems to be no way to make it show the (for example) year in the tick where it changes, while only showing the month in subsequent ones

https://codepen.io/plotly/pen/roZORo

**Comment by wrowlands3** [comment]
> After some trial and error, I got this, but it is too ugly to use. Help welcomed :) ![custom x axis formatting](https://user-images.githubusercontent.com/777196/198838075-98e6a930-db84-4f07-8eee-09a3790c1442.gif) [ ![custom x axis formatting](https://user-images.githubusercontent.com/777196/198838075-98e6a930-db84-4f07-8eee-09a3790c1442.gif) ](https://user-images.githubusercontent.com/777196/198838075-98e6a930-db84-4f07-8eee-09a3790c1442.gif) [ ](https://user-images.githubusercontent.com/777196/198838075-98e6a930-db84-4f07-8eee-09a3790c1442.gif)
> 
> The issue here, is that the axis labels can not be set while scrolling/zooming

@dbuezas How did you format the yaml for tickformatstops? I've tried to use the example you posted but cannot seem to get any tickformatstops to work.

**Comment by dbuezas** [comment]
> How did you format the yaml for tickformatstops?

https://github.com/dbuezas/lovelace-plotly-graph-card/compare/master...experiment/custom-date-formatter#diff-c0352c6cdab9f9d6e1251e51657ccfc84873e2c7b361622d9aa4094c04c11093

At the moment it can't be done with yaml alone. Soon it will be possible, once #130 is finished.

**Comment by dbuezas** [comment]
I gave up on this. I'll close it, but feel free to open it again if you have any new implementation idea :)
