### ISSUE TITLE
card-mod support

### ISSUE THREAD

**Issue by FrnchFrgg** [dbuezas/lovelace-plotly-graph-card#86]
Currently, `plotly-graph` is not compatible with `card-mod`. I think there are two ways of making it compatible. A way which will work only with `card-mod`, and another which should make `plotly-graph` sufficiently similar to a vanilla card that `card-mod` and any other similar mod will work.

The first way is to call some `card-mod` primitive yourself so that it can do its magic. See https://github.com/thomasloven/lovelace-card-mod/blob/master/README-developers.md where AFAICT `el` should be the `<ha-card/>`, `type` should be what you want it to be (probably `plotly-graph` but you can use `card` which is what `card-mod` uses when it can hook into the `ha-card` itself as in the complicated method), `styles` should be `config?.card_mod?.style || config?.style || ""` where `config` is the whole card configuration, `variables` should be `{ config }`, the unused should be `null`, and the last one I think should be `false`.

See https://github.com/thomasloven/lovelace-card-mod/blob/master/src/patch/ha-card.ts#L25 which is what `card-mod` wants `ha-card` to do when it is patched. I do not know if and when you are supposed to use the returned object to call its `refresh()` method as the patched `ha-card` does.

The other way is to make `plotly-card` extend `LitElement` instead of `HTMLElement`, as `apexcharts-card` does here: https://github.com/RomRider/apexcharts-card/blob/master/src/apexcharts-card.ts#L116. Another much simpler example to get inspiration from is https://github.com/thomasloven/lovelace-card-mod/blob/master/src/mod-card.ts whose role is only to wrap elements without an inner `<ha-card/>` into one.

But maybe the only thing that makes a `LitElement` work as-is with `card-mod` and your `HTMLElement`-based card not is that you do not provide any `update()` method ? Maybe adding a dummy `update()` would magically make things work ? I'll have to try if you do not get to do it before me.

Note that I never programmed in TypeScript before so I am very slow and naive. Sorry for that.

**Comment by FrnchFrgg** [comment]
In fact, I would bet on just providing a dummy `update()` method just for `card-mod` because its `setConfig` hack works so it can find your own `setConfig()`. The proof is that when changing the configuration while editing the card makes the `card-mod` settings apply.

**Comment by FrnchFrgg** [comment]
Your fix is not enough. I will try with the dev version of `plotly-graph` to see what causes the problem. Maybe that's just because `setConfig()` is called too soon (before the `ha-card` is created and thus the `setConfig()` gets patched) ? When editing, each change means a call to `setConfig()` and that makes the thing work.

In fact, it seems that `card-mod` works (since it attaches its `<style/>` placeholders) but does not see its configuration. As it searches for it in the `ha-card` ancestors `config` attribute, maybe your `setConfig()`, while called too soon for the patched version to kick in, is called too late for the `config` attribute to be filled when `card-mod` sets itself up in the `ha-card` ?

**Comment by dbuezas** [comment]
Oh, you are right, card-mod is looking for the ha-card element, and that one is added later on connectedCallback.

**Comment by dbuezas** [comment]
I think setting the html can be done in the constructor already, and initialisation can happen on connectedCallback, then it should work.
Then the dummy updated function may be unnecessary too

**Comment by dbuezas** [comment]
Or maybe the whole HTMLElement should ve an ha-card?

**Comment by FrnchFrgg** [comment]
This is still not working. The ordering of calls is 1) constructor 2) unpatched setConfig 3) connect [setConfig is still unpatched] 4) disconnect 5) connect [again setConfig unpatched].

If I add `window.setTimeout(() => this.setConfig(config), 100);` at the to of `setConfig` (guarded by a test whether it is patched or not to avoid repeating ad nauseam) then the first delayed `setConfig` is patched, and `card-mod` works.

**Comment by FrnchFrgg** [comment]
Note that `card-mod` would work if you saved the `config` argument to `setConfig` into `this.config` instead of saving the parsed one. The real problem is that `card-mod` finds the config with this method: https://github.com/thomasloven/lovelace-card-mod/blob/06140ff020e94a20f7eec9f51c18ad04aef0e8f1/src/helpers.ts#L121

And you do not save the original config where it looks. Maybe you should save the original config in `this.config` and use `this._config` for the parsed one ? Or another name altogether. Just saving the original config in `this._config` is not going to work due to the lookup ordering.

**Comment by dbuezas** [comment]
Oh that would be enough? So i can undo the rest? That's easy. I could also copy whatever alien properties to my parsed one, it's one line

**Comment by FrnchFrgg** [comment]
Indeed, I just tested and simply replacing
```
    const newConfig: Config = {
```
by
```
    const newConfig: Config = {
      ...config,
```
in `setConfig()` does the trick. It would have an unintended effect though: the variables accessible in the `card-mod` style template would be the interpreted config, not the raw one. It may confuse some people to get your defaults in some of them instead of just what they actually put in the card YAML.

**Comment by dbuezas** [comment]
Oh yes, that's exactly what I meant. But you are right with the caveat.
If you want, feel free to make a PR, just right click, rename symbol, and then you can store the original config in the instance.
