### ISSUE TITLE
"fill: tonexty" broken when "show_value" is used 

### ISSUE THREAD

**Issue by dbuezas** [dbuezas/lovelace-plotly-graph-card#87]
> I tried with the "Try it on CodePen" button of the first example here https://plotly.com/javascript/line-charts/#basic-line-plot by adding `fill: 'tonexty'` to `trace2` and it works here. In HA, adding `fill: tonexty` at the same level as the `entity` works here and links with the previous entity in the yaml list. Warning: AFAICT it links to the previous one that is enabled. If you disable it in the legend then it links to the previous one and so on.

It makes me crazy... i can do it outside HA, but not inside...
Here is one of my example:
`
  - entity: sensor.ths_fridge_humidity
      name: φ[%] (max)
      fill: none
      line:
        color: rgba(143, 86, 164, 0.6)
        width: 1
      statistic: max
      period: 1day
      showlegend: true
      
    - entity: sensor.ths_fridge_humidity
      fill: tonexty
      name: φ[%] (min)
      line:
        color: rgba(143, 86, 164, 0.6)
        width: 1
      statistic: min
      period: 1day
      showlegend: true
      
    - entity: sensor.ths_fridge_humidity
      fill: none
      name: φ[%] (mean)
      line:
        color: rgba(143, 86, 164, 1.0)
      statistic: mean
      period: 4hour`

The result:
![2022-10-27 11_16_01-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198244778-be9318ae-415d-40d6-bfbf-46c62889d08d.png)
I think I was exhaustive in trying different combinations of fill, order of entities, but I get similar results....

_Originally posted by @r-jean-pierre in https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/75#discussioncomment-3979606_

**Comment by dbuezas** [comment]
Thanks for the confirmation.
Tip:
```yaml
defaults:
  entity:
    texttemplate: "%{y:.2f}" # will only show 2 decimals of the value
    show_value: true 
```

See more here: https://plotly.com/javascript/reference/pie/#pie-texttemplate

**Comment by dbuezas** [comment]
By the way, that color palette looks so nice! Can I use that screenshot in the main page?

**Comment by dbuezas** [comment]
Also, I'm sure others will too like to see your yaml posted here:
https://github.com/dbuezas/lovelace-plotly-graph-card/discussions/81#discussioncomment-3984289

**Comment by r-jean-pierre** [comment]
Here is the picture:
![2022-10-27 19_34_33-YAML Dashboard – Home Assistant](https://user-images.githubusercontent.com/9727894/198359687-50c7c682-f621-49ea-baad-6474b11248a8.png)
