### ISSUE TITLE
use local time format

### ISSUE THREAD

**Issue by Bascht74** [dbuezas/lovelace-plotly-graph-card#89]
as wished in https://github.com/dbuezas/lovelace-plotly-graph-card/issues/85 :

Could the date be shown in the localized format?

Right now it is in english with your card, but I set it to the german way in my profile settings:
![image](https://user-images.githubusercontent.com/66269310/197835134-298f398f-c9ad-4fac-8f37-44574418f25d.png)

German in profile, english in the card:
![image](https://user-images.githubusercontent.com/66269310/197834160-56f1cae3-c7ec-4fb6-9e9f-eaaf13ee5750.png)

Thx for your great work,

Sebastian

**Comment by dbuezas** [comment]
Thanks for the nice words :)

This can be done, but it will only pay attention to the language.
For future reference:
* import plotly locales: https://github.com/plotly/plotly.js/tree/master/dist (search for locale)
* HA locale: this.hass?.locale?.language
* Plotly locale setting (config.locale) https://plotly.com/javascript/configuration-options/#change-the-default-locale

**Comment by dbuezas** [comment]
Hey @Bascht74 I made a beta release with support for locales. See [here](https://github.com/dbuezas/lovelace-plotly-graph-card/releases/tag/v3.3.0).

Do you mind giving some feedback?

To install see [Enable beta for a repository in HACS](https://hacs.xyz/docs/faq/beta/)
